#!/bin/bash

# Exit on error
set -e

# Function to prompt for input with a default value
prompt_input() {
    local prompt="$1"
    local default="$2"
    read -p "$prompt [$default]: " input
    echo "${input:-$default}"
}

# Function to prompt for a yes/no question
prompt_yes_no() {
    local prompt="$1"
    local default="$2"
    while true; do
        read -p "$prompt [$default]: " input
        input=${input:-$default}
        case $input in
            [Yy]|[Yy][Ee][Ss]) return 0 ;;
            [Nn]|[Nn][Oo]) return 1 ;;
            *) echo "Please answer yes or no." ;;
        esac
    done
}

# Get filename for the configuration
filename=$(prompt_input "Enter the output filename (without .yaml extension)" "custom-netplan")
output_file="${filename}.yaml"

# Get bond name
bond_name=$(prompt_input "Enter the bond interface name" "bond0")

# Get network interfaces
echo "Enter the network interfaces (comma-separated, e.g. eth0,eth1):"
read interfaces_input
IFS=',' read -ra interfaces <<< "$interfaces_input"

# Get IP addresses for the bond
ip_addresses=$(prompt_input "Enter IP addresses for the bond (comma-separated)" "1.2.3.4/31,10.0.0.100/31,192.168.0.100/32")
# Format IP addresses
IFS=',' read -ra ip_array <<< "$ip_addresses"
formatted_ips=""
for ip in "${ip_array[@]}"; do
    formatted_ips="$formatted_ips\"$ip\", "
done
formatted_ips=${formatted_ips%, }  # Remove trailing comma and space

# Get gateway
gateway=$(prompt_input "Enter the gateway" "10.0.0.1")

# Get nameservers
nameservers=$(prompt_input "Enter nameservers (comma-separated)" "8.8.8.8,8.8.4.4,1.1.1.1")
# Format nameservers
IFS=',' read -ra ns_array <<< "$nameservers"
formatted_ns=""
for ns in "${ns_array[@]}"; do
    formatted_ns="$formatted_ns\"$ns\", "
done
formatted_ns=${formatted_ns%, }  # Remove trailing comma and space

# Generate Netplan configuration
cat > "$output_file" << EOL
# Netplan configuration generated by script
network:
  version: 2
  renderer: networkd
  ethernets:
EOL

for iface in "${interfaces[@]}"; do
    cat >> "$output_file" << EOL
    ${iface}:
      dhcp4: no
      dhcp6: no
EOL
done

cat >> "$output_file" << EOL

  bonds:
    ${bond_name}:
      addresses: [${formatted_ips}]
      gateway4: ${gateway}
      interfaces:
EOL

for iface in "${interfaces[@]}"; do
    echo "        - ${iface}" >> "$output_file"
done

cat >> "$output_file" << EOL

      parameters:
        mode: 802.3ad
        transmit-hash-policy: layer3+4
        mii-monitor-interval: 100
      nameservers:
        addresses: [${formatted_ns}]
EOL

echo "Netplan configuration generated at $output_file"

# Ask if user wants to preview the file
if prompt_yes_no "Do you want to preview the generated file?" "yes"; then
    cat "$output_file"
fi

# Ask if user wants to apply the configuration
if prompt_yes_no "Do you want to copy this file to /etc/netplan/?" "no"; then
    sudo cp "$output_file" "/etc/netplan/"
    echo "File copied to /etc/netplan/$output_file"
    echo "You are now ready to test or apply the configuration with 'sudo netplan apply'."
fi